### ISSUE TITLE
Unable to open tab

### ISSUE THREAD

**Issue by UncleSamSwiss** [ioBroker/ioBroker.fullcalendar#335]
**Describe the bug**  
When trying to open the "Calendar" tab, the right side stays empty.

**To Reproduce**  
1. Open the tab

**Expected behavior**  
The calendar is visible

**Screenshots & Logfiles**  
![image](https://github.com/user-attachments/assets/6817b1ca-4007-4452-bc19-90a6bdbc3fdd)

The following two errors are shown in the developer console:
```
react-dom.production.min.js:188 TypeError: Cannot read properties of undefined (reading 'palette')
    at iv (Calendar.js:423:26)
    at gr (react-dom.production.min.js:160:137)
    at Si (react-dom.production.min.js:289:337)
    at xl (react-dom.production.min.js:279:389)
    at zl (react-dom.production.min.js:279:320)
    at gl (react-dom.production.min.js:279:180)
    at rl (react-dom.production.min.js:270:88)
    at ol (react-dom.production.min.js:267:429)
    at y (scheduler.production.min.js:13:203)
    at MessagePort.L (scheduler.production.min.js:14:128)
us @ react-dom.production.min.js:188
c.callback @ react-dom.production.min.js:188
Go @ react-dom.production.min.js:156
Hi @ react-dom.production.min.js:261
xi @ react-dom.production.min.js:259
Mi @ react-dom.production.min.js:258
(anonymous) @ react-dom.production.min.js:282
yl @ react-dom.production.min.js:280
ol @ react-dom.production.min.js:269
y @ scheduler.production.min.js:13
L @ scheduler.production.min.js:14
Show 11 more frames
Show lessUnderstand this error
Calendar.js:423 Uncaught TypeError: Cannot read properties of undefined (reading 'palette')
    at iv (Calendar.js:423:26)
    at gr (react-dom.production.min.js:160:137)
    at Si (react-dom.production.min.js:289:337)
    at xl (react-dom.production.min.js:279:389)
    at zl (react-dom.production.min.js:279:320)
    at gl (react-dom.production.min.js:279:180)
    at rl (react-dom.production.min.js:270:88)
    at ol (react-dom.production.min.js:267:429)
    at y (scheduler.production.min.js:13:203)
    at MessagePort.L (scheduler.production.min.js:14:128)
```

**Versions:**  
 - Adapter version: 2.4.2	
 - JS-Controller version: 6.0.11
 - Admin version: 7.1.5
 - Node version: v18.20.4
 - Operating system: docker (official image - v9.1.2)

**Comment by bubiman** [comment]
Apperantly this is fixed in 2.4.5 https://github.com/ioBroker/ioBroker.fullcalendar/issues/284
